version: '2'
services:
  hitchhiker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hitchhiker
    environment:
      - HITCHHIKER_DB_HOST=hitchhiker-mysql
      - HITCHHIKER_APP_HOST=http://localhost:8080/ # should change before deploying.
      # add environment variable to config
    ports:
      - "8080:8080"
      - "11010:11010"
    links:
      - hitchhiker-mysql:hitchhiker-mysql
    volumes:
      - $HOME/hitchhiker/data:/usr/src/Hitchhiker/build/global_data/project
      - $HOME/hitchhiker/backup:/usr/src/Hitchhiker/build/backup
      - $HOME/hitchhiker/logs:/usr/src/Hitchhiker/build/logs
  hitchhiker-mysql:
    image: mysql:5.7
    container_name: hitchhiker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hitchhiker888
      - MYSQL_DATABASE=hitchhiker-prod
    volumes:
      - ./hitchhiker-mysql.cnf:/etc/mysql/conf.d/hitchhiker.cnf
      - $HOME/hitchhiker/sqldata:/var/lib/mysql